// Auto-generated from PreparedLearnAssets/LEARN_CONTENT_MASTER.md — do not edit by hand.
import SwiftUI

enum LearnCategory: String, CaseIterable, Identifiable, Hashable {
    case overview = "Overview"
    case anatomy = "Anatomy"
    case functionality = "Functionality"
    case realLife = "Real Life"
    case clinicalInsight = "Clinical Insight"
    case summary = "Summary"
    var id: String { rawValue }
    var symbol: String {
        switch self {
        case .overview: "book"
        case .anatomy: "square.stack.3d.up"
        case .functionality: "bolt.heart"
        case .realLife: "figure.walk"
        case .clinicalInsight: "stethoscope"
        case .summary: "checkmark.seal"
        }
    }
}

struct LearnChapter: Identifiable, Hashable {
    let id: String
    let organID: String
    let title: String
    let category: LearnCategory
    let imageName: String
    let imageLeft: Bool
    let learningGoal: String
    let explanation: String
    let keyFacts: [String]
    let caption: String
    let checkQuestion: String
    let labels: [String]
    var quizTopic: String { title }
}

enum LearnCurriculum {
    static let heart: [LearnChapter] = [
        LearnChapter(id: "heart_overview", organID: "heart", title: "Meet the Heart", category: .overview, imageName: "heart_overview", imageLeft: true, learningGoal: "Understand what the heart is and why it is central to survival.", explanation: "The heart is a muscular pump that keeps blood moving through the lungs and the rest of the body. Every beat delivers oxygen, nutrients, and chemical signals to tissues while carrying waste away. In Learn Mode, the heart is introduced first as a complete organ before its internal parts are broken down.", keyFacts: ["The heart sits slightly left of center in the chest.", "It works continuously, beating thousands of times each day.", "Its main job is to keep oxygen-poor and oxygen-rich blood moving in the correct direction."], caption: "A full view of the heart as the body’s central pump.", checkQuestion: "Which organ acts as the main muscular pump of the circulatory system?", labels: ["Heart"]),
        LearnChapter(id: "heart_chambers", organID: "heart", title: "The Four Chambers", category: .anatomy, imageName: "heart_chambers", imageLeft: false, learningGoal: "Learn the names and roles of the four chambers.", explanation: "The heart has four chambers that separate incoming and outgoing blood. The right side receives oxygen-poor blood and sends it to the lungs, while the left side receives oxygen-rich blood and pushes it to the body. Understanding the chambers helps learners follow blood flow more easily in later chapters.", keyFacts: ["The atria are the upper receiving chambers.", "The ventricles are the lower pumping chambers.", "The left ventricle has the thickest muscular wall because it pumps blood to the whole body."], caption: "The heart’s four chambers organize how blood enters and leaves the organ.", checkQuestion: "Which chamber pumps oxygen-rich blood into the systemic circulation?", labels: ["Right Atrium", "Right Ventricle", "Left Atrium", "Left Ventricle"]),
        LearnChapter(id: "heart_valves", organID: "heart", title: "The One-Way Valves", category: .anatomy, imageName: "heart_valves", imageLeft: true, learningGoal: "Understand how valves keep blood moving in only one direction.", explanation: "Valves open when pressure pushes blood forward and close to prevent backward flow. This one-way system helps each chamber work efficiently and keeps circulation coordinated. When valves fail to close properly, the heart has to work harder.", keyFacts: ["Valves act like doors that open and shut with pressure changes.", "The atrioventricular valves sit between atria and ventricles.", "The semilunar valves sit at the exits to the major arteries."], caption: "Heart valves direct blood forward and stop backflow.", checkQuestion: "Which valve separates the left atrium from the left ventricle?", labels: ["Mitral Valve", "Tricuspid Valve", "Aortic Valve", "Pulmonary Valve"]),
        LearnChapter(id: "heart_blood_flow", organID: "heart", title: "The Blood Flow Journey", category: .functionality, imageName: "heart_blood_flow", imageLeft: false, learningGoal: "Follow the path blood takes through the heart, lungs, and body.", explanation: "Blood enters the right side of the heart after returning from the body, then travels to the lungs to pick up oxygen. It returns to the left side and is pumped out to the body again. This looping pattern makes the heart a bridge between the lungs and the tissues they support.", keyFacts: ["Oxygen-poor blood travels to the lungs.", "Oxygen-rich blood returns to the left side of the heart.", "The right and left sides of the heart support two linked circulation loops."], caption: "Blood moves through the heart in a repeating right-to-lungs-to-left-to-body cycle.", checkQuestion: "What is the correct order of major blood flow steps?", labels: ["Body", "Right Atrium", "Right Ventricle", "Lungs", "Left Atrium", "Left Ventricle"]),
        LearnChapter(id: "heart_coronary_vessels", organID: "heart", title: "The Heart’s Own Blood Supply", category: .anatomy, imageName: "heart_coronary_vessels", imageLeft: true, learningGoal: "Understand that the heart muscle needs its own blood vessels.", explanation: "Even though the heart pumps blood for the whole body, its muscle cannot absorb enough oxygen directly from the blood inside its chambers. Instead, coronary arteries deliver oxygen and nutrients to the heart wall itself. Coronary veins then help carry used blood away.", keyFacts: ["Coronary arteries wrap around the surface of the heart.", "The heart muscle depends on a constant oxygen supply.", "Blocked coronary arteries can damage heart tissue quickly."], caption: "Coronary vessels feed the heart muscle that powers every heartbeat.", checkQuestion: "What blood vessels supply the heart muscle itself?", labels: ["Coronary Artery", "Coronary Vein", "Aorta"]),
        LearnChapter(id: "heart_conduction_system", organID: "heart", title: "The Electrical System", category: .functionality, imageName: "heart_conduction_system", imageLeft: false, learningGoal: "Learn how electrical signals coordinate the heartbeat.", explanation: "The heart contracts because specialized cells generate and spread electrical signals. The sinoatrial node starts the rhythm, the atrioventricular node briefly delays it, and the signal then moves through conducting fibers into the ventricles. This timing ensures the chambers squeeze in an efficient sequence.", keyFacts: ["The sinoatrial node acts as the natural pacemaker.", "A short delay lets the ventricles fill before they contract.", "Conducting fibers help the ventricles squeeze from the bottom upward."], caption: "Electrical signals guide the order and timing of each heartbeat.", checkQuestion: "Which structure normally starts the heartbeat?", labels: ["SA Node", "AV Node", "Bundle Branches", "Purkinje Fibers"]),
        LearnChapter(id: "heart_exercise_response", organID: "heart", title: "The Heart During Exercise", category: .realLife, imageName: "heart_exercise_response", imageLeft: true, learningGoal: "See how the heart adapts when the body needs more oxygen.", explanation: "During exercise, muscles demand more oxygen and produce more carbon dioxide. The heart responds by beating faster and more forcefully, pushing more blood through the lungs and into active tissues. This flexible response helps maintain performance during movement.", keyFacts: ["Heart rate rises during physical activity.", "Stroke volume can increase as the heart pumps harder.", "Greater cardiac output supports working muscles."], caption: "The heart adjusts its output to match the body’s changing needs.", checkQuestion: "What happens to heart rate during exercise?", labels: ["Heart Rate", "Cardiac Output", "Active Muscle"]),
        LearnChapter(id: "heart_attack", organID: "heart", title: "What Happens During a Heart Attack", category: .clinicalInsight, imageName: "heart_attack", imageLeft: false, learningGoal: "Understand the basic idea of a blocked coronary artery.", explanation: "A heart attack happens when part of the heart muscle loses its blood supply, usually because a coronary artery becomes blocked. Without oxygen, heart tissue can become damaged. This chapter introduces the concept in a calm educational way and reinforces why coronary blood flow matters.", keyFacts: ["Coronary blockage reduces oxygen delivery to heart muscle.", "Damage often affects only the region supplied by the blocked vessel.", "Fast restoration of blood flow is important in real medical care."], caption: "Reduced coronary blood flow can injure the heart muscle it serves.", checkQuestion: "What is being blocked during a heart attack?", labels: ["Blocked Coronary Artery", "Reduced Blood Flow", "Heart Muscle"]),
        LearnChapter(id: "heart_summary", organID: "heart", title: "Heart Summary", category: .summary, imageName: "heart_summary", imageLeft: true, learningGoal: "Review the heart’s structure and function in one visual recap.", explanation: "The heart is a four-chambered pump with valves, coronary vessels, and an electrical system that work together to support circulation. By reviewing the whole organ after the details, learners can reconnect structure and function into a complete mental model.", keyFacts: ["Chambers organize blood movement.", "Valves maintain one-way flow.", "Electrical and vascular systems support reliable pumping."], caption: "A recap of the heart’s key systems and roles.", checkQuestion: "Match the heart’s main systems with their functions?", labels: ["Chambers", "Valves", "Coronary Vessels", "Conduction"]),
    ]

    static let brain: [LearnChapter] = [
        LearnChapter(id: "brain_overview", organID: "brain", title: "Meet the Brain", category: .overview, imageName: "brain_overview", imageLeft: true, learningGoal: "Understand the brain as the control center of the nervous system.", explanation: "The brain receives information, interprets it, and coordinates responses across the body. It supports movement, sensation, memory, language, emotion, and survival functions. Learn Mode begins with the whole organ so later chapters can connect specific regions to their roles.", keyFacts: ["The brain communicates with the body through the nervous system.", "Different regions specialize in different tasks.", "The brain works continuously, even during sleep."], caption: "The brain acts as the body’s central processing and control organ.", checkQuestion: "Which organ coordinates sensation, thought, and movement?", labels: ["Brain"]),
        LearnChapter(id: "brain_cerebrum", organID: "brain", title: "The Cerebrum", category: .anatomy, imageName: "brain_cerebrum", imageLeft: false, learningGoal: "Recognize the cerebrum as the largest part of the brain.", explanation: "The cerebrum forms the broad upper portion of the brain and supports higher functions such as thought, planning, language, sensation, and voluntary movement. Its folded surface increases the amount of processing tissue that fits inside the skull.", keyFacts: ["The cerebrum is the largest brain region.", "Its two hemispheres work together but also show some specialization.", "Surface folds increase cortical area."], caption: "The cerebrum is the brain’s largest and most complex region.", checkQuestion: "Which major brain region supports higher thinking and voluntary action?", labels: ["Cerebrum", "Left Hemisphere", "Right Hemisphere"]),
        LearnChapter(id: "brain_frontal_lobe", organID: "brain", title: "Planning and Decision-Making", category: .anatomy, imageName: "brain_frontal_lobe", imageLeft: true, learningGoal: "Learn the role of the frontal lobe in organized behavior.", explanation: "The frontal lobe helps with planning, judgment, attention, and voluntary control of movement. It contributes to the decisions we make and the actions we choose. In everyday life, it helps turn goals into organized steps.", keyFacts: ["The frontal lobe supports executive function.", "It contributes to personality and social behavior.", "It contains important motor planning regions."], caption: "The frontal lobe helps shape action, planning, and self-control.", checkQuestion: "Which lobe is most associated with planning and decision-making?", labels: ["Frontal Lobe"]),
        LearnChapter(id: "brain_parietal_lobe", organID: "brain", title: "Touch and Spatial Awareness", category: .anatomy, imageName: "brain_parietal_lobe", imageLeft: false, learningGoal: "Understand the parietal lobe’s role in body awareness and sensation.", explanation: "The parietal lobe helps the brain interpret touch, pressure, temperature, and body position. It also contributes to spatial awareness, allowing people to judge where objects are and how the body moves through space.", keyFacts: ["The parietal lobe processes many sensory signals.", "It helps integrate information from different senses.", "It supports awareness of position and movement."], caption: "The parietal lobe helps build an internal map of body and space.", checkQuestion: "Which lobe helps with touch and spatial awareness?", labels: ["Parietal Lobe"]),
        LearnChapter(id: "brain_temporal_lobe", organID: "brain", title: "Memory and Language", category: .anatomy, imageName: "brain_temporal_lobe", imageLeft: true, learningGoal: "Learn how the temporal lobe supports hearing, memory, and language.", explanation: "The temporal lobe is important for processing sound and for building and retrieving memories. It also supports understanding language. This makes it a key region for communication and learning.", keyFacts: ["The temporal lobe helps process auditory information.", "It plays a major role in memory formation.", "It supports language comprehension."], caption: "The temporal lobe helps connect sound, memory, and meaning.", checkQuestion: "Which lobe is strongly linked to memory and language?", labels: ["Temporal Lobe"]),
        LearnChapter(id: "brain_occipital_lobe", organID: "brain", title: "Vision Processing", category: .anatomy, imageName: "brain_occipital_lobe", imageLeft: false, learningGoal: "Understand the occipital lobe as the main visual processing region.", explanation: "The occipital lobe receives and interprets visual signals arriving from the eyes. It helps the brain recognize shape, movement, contrast, and spatial relationships in what we see.", keyFacts: ["The occipital lobe is located near the back of the brain.", "It is specialized for visual information processing.", "It helps transform light signals into meaningful perception."], caption: "The occipital lobe converts visual input into usable information.", checkQuestion: "Which lobe is most closely associated with vision?", labels: ["Occipital Lobe"]),
        LearnChapter(id: "brain_cerebellum", organID: "brain", title: "Balance and Coordination", category: .anatomy, imageName: "brain_cerebellum", imageLeft: true, learningGoal: "Learn how the cerebellum refines movement.", explanation: "The cerebellum helps coordinate timing, balance, and precision. Rather than starting movement itself, it fine-tunes actions so they are smooth and controlled. This makes it essential for posture, walking, and skilled motion.", keyFacts: ["The cerebellum helps maintain balance.", "It refines muscle activity for precision.", "It contributes to motor learning through practice."], caption: "The cerebellum helps the body move smoothly and accurately.", checkQuestion: "Which structure is especially important for balance and coordination?", labels: ["Cerebellum"]),
        LearnChapter(id: "brain_brainstem", organID: "brain", title: "Survival Functions", category: .anatomy, imageName: "brain_brainstem", imageLeft: false, learningGoal: "Understand why the brainstem is essential for life.", explanation: "The brainstem connects the brain to the spinal cord and manages basic functions such as breathing, heart rate, and alertness. Because it supports vital automatic processes, it is one of the most important pathways in the nervous system.", keyFacts: ["The brainstem links the brain and spinal cord.", "It helps regulate breathing and circulation.", "It supports wakefulness and automatic survival functions."], caption: "The brainstem helps maintain essential life-supporting functions.", checkQuestion: "Which brain region is most involved in breathing and heart rate regulation?", labels: ["Midbrain", "Pons", "Medulla", "Spinal Cord"]),
        LearnChapter(id: "brain_memory_learning", organID: "brain", title: "Memory and Learning", category: .functionality, imageName: "brain_memory_learning", imageLeft: true, learningGoal: "Connect memory formation to brain structures involved in learning.", explanation: "Learning changes the brain by strengthening patterns of activity and connection. Memory-related systems help new experiences become stored information that can later be recalled. This chapter gives learners a functional bridge between anatomy and behavior.", keyFacts: ["Memory depends on networks rather than one single point.", "Repetition helps strengthen learned pathways.", "Attention and sleep both support memory formation."], caption: "Memory and learning rely on coordinated brain systems.", checkQuestion: "Which brain function improves when learning becomes stored as memory?", labels: ["Hippocampus", "Cortex", "Memory Pathway"]),
        LearnChapter(id: "brain_sleep_consciousness", organID: "brain", title: "Sleep and Consciousness", category: .functionality, imageName: "brain_sleep_consciousness", imageLeft: false, learningGoal: "Understand that the brain remains active during sleep and wakefulness cycles.", explanation: "Sleep is not a shutdown state. The brain continues to regulate rhythms, restore balance, and organize information. Consciousness, attention, and sleep all depend on coordinated activity across several systems.", keyFacts: ["The brain controls daily sleep-wake timing.", "Sleep supports memory, recovery, and regulation.", "Consciousness depends on widespread coordinated brain activity."], caption: "The brain actively shapes both wakefulness and sleep.", checkQuestion: "What important role the brain plays during sleep?", labels: ["Circadian Rhythm", "Sleep-Wake Cycle", "Brain Activity"]),
        LearnChapter(id: "brain_clinical_insight", organID: "brain", title: "Brain Health and Injury", category: .clinicalInsight, imageName: "brain_clinical_insight", imageLeft: true, learningGoal: "Introduce how injury or disease can affect brain function.", explanation: "Brain health depends on blood supply, protection, and healthy neural activity. Injury or disease can alter movement, memory, language, sensation, or consciousness depending on which areas are affected. This chapter keeps the focus educational, not alarming.", keyFacts: ["Different brain regions produce different symptoms when damaged.", "Brain tissue is highly sensitive to interrupted blood flow.", "Protective habits and rapid medical care can make a major difference."], caption: "Brain structure and brain function are closely linked in health and injury.", checkQuestion: "Why damage in different brain areas can produce different effects?", labels: ["Healthy Brain Tissue", "Injured Region", "Blood Supply"]),
        LearnChapter(id: "brain_summary", organID: "brain", title: "Brain Summary", category: .summary, imageName: "brain_summary", imageLeft: false, learningGoal: "Review the brain’s major regions and functions in one recap.", explanation: "The brain combines specialized regions into one integrated control system. By the end of this sequence, learners should understand how the cerebrum, lobes, cerebellum, and brainstem each contribute to perception, movement, memory, and survival.", keyFacts: ["Major regions work together rather than in isolation.", "Structure helps explain function.", "Understanding regional roles improves interpretation of symptoms and behavior."], caption: "A recap of the brain’s major regions and what they do.", checkQuestion: "Match major regions with their core functions?", labels: ["Cerebrum", "Cerebellum", "Brainstem", "Lobes"]),
    ]

    static let lungs: [LearnChapter] = [
        LearnChapter(id: "lungs_overview", organID: "lungs", title: "Meet the Lungs", category: .overview, imageName: "lungs_overview", imageLeft: true, learningGoal: "Understand the lungs as the main organs of gas exchange.", explanation: "The lungs bring oxygen into the body and help remove carbon dioxide. They work closely with the heart and blood vessels to keep tissues supplied with the gases needed for energy. Learn Mode begins with the full organ before moving inward to smaller airways and air sacs.", keyFacts: ["The lungs fill much of the chest cavity.", "They exchange gases between air and blood.", "Breathing depends on lung tissue, airways, and respiratory muscles working together."], caption: "The lungs make gas exchange possible with every breath.", checkQuestion: "What the lungs exchange with the blood?", labels: ["Lungs"]),
        LearnChapter(id: "lungs_airways", organID: "lungs", title: "The Airway Tree", category: .anatomy, imageName: "lungs_airways", imageLeft: false, learningGoal: "Learn how air travels from the throat into the lungs.", explanation: "Air enters through larger tubes and then passes into branching airways inside the lungs. This tree-like pattern helps distribute air broadly and efficiently. The airway path is the first step in delivering oxygen to the deepest gas-exchange surfaces.", keyFacts: ["The airway pathway starts with the trachea.", "The bronchi divide into smaller tubes as they enter the lungs.", "Branching increases surface access to lung tissue."], caption: "The airway tree carries inhaled air toward the gas-exchange surfaces.", checkQuestion: "Which structure carries air downward before it splits into the bronchi?", labels: ["Trachea", "Bronchi", "Bronchioles", "Lungs"]),
        LearnChapter(id: "lungs_bronchi_bronchioles", organID: "lungs", title: "Branching Airways", category: .anatomy, imageName: "lungs_bronchi_bronchioles", imageLeft: true, learningGoal: "See how large airways become smaller conducting passages.", explanation: "After entering the lungs, the bronchi divide again and again into bronchioles. This branching system spreads inhaled air across a huge internal surface area. Smaller airway size also helps control airflow and resistance.", keyFacts: ["Bronchi are larger and more rigid than bronchioles.", "Bronchioles lead air toward the alveoli.", "Airway narrowing can strongly affect breathing."], caption: "Bronchi and bronchioles distribute air throughout the lungs.", checkQuestion: "Which airway comes after the bronchi in the branching pathway?", labels: ["Bronchi", "Bronchioles", "Terminal Airways"]),
        LearnChapter(id: "lungs_alveoli", organID: "lungs", title: "Alveoli: Tiny Air Sacs", category: .anatomy, imageName: "lungs_alveoli", imageLeft: false, learningGoal: "Understand where gas exchange actually happens.", explanation: "Alveoli are tiny air sacs with extremely thin walls. They are surrounded by capillaries, allowing oxygen and carbon dioxide to move quickly between air and blood. Their huge total surface area makes breathing efficient.", keyFacts: ["Alveoli are the main sites of gas exchange.", "Capillaries wrap closely around alveolar surfaces.", "Thin membranes help gases diffuse rapidly."], caption: "Alveoli and capillaries meet at the key exchange surface of respiration.", checkQuestion: "Which tiny structure in the lungs is specialized for gas exchange?", labels: ["Alveoli", "Capillaries", "Oxygen", "Carbon Dioxide"]),
        LearnChapter(id: "lungs_gas_exchange", organID: "lungs", title: "Oxygen and Carbon Dioxide Exchange", category: .functionality, imageName: "lungs_gas_exchange", imageLeft: true, learningGoal: "Follow the direction of gas movement between lungs and blood.", explanation: "Oxygen moves from inhaled air into the blood, while carbon dioxide moves from the blood into the alveoli to be exhaled. This exchange happens because of pressure differences across very thin membranes. It is the central function of the respiratory system.", keyFacts: ["Oxygen moves into blood in the lungs.", "Carbon dioxide moves out of blood into the alveoli.", "Efficient gas exchange depends on healthy alveoli and capillaries."], caption: "Gas exchange moves oxygen in and carbon dioxide out.", checkQuestion: "Which gas leaves the blood to be exhaled?", labels: ["Oxygen", "Carbon Dioxide", "Alveolus", "Blood Capillary"]),
        LearnChapter(id: "lungs_breathing_mechanics", organID: "lungs", title: "Diaphragm and Breathing", category: .functionality, imageName: "lungs_breathing_mechanics", imageLeft: false, learningGoal: "Understand how the body physically draws air in and pushes it out.", explanation: "Breathing depends on changes in chest volume. When the diaphragm contracts and moves downward, the chest cavity expands and air is drawn in. When it relaxes, the lungs recoil and air moves out.", keyFacts: ["The diaphragm is the main breathing muscle.", "Expansion of the chest helps pull air inward.", "Elastic recoil helps move air outward during exhalation."], caption: "The diaphragm changes chest volume to drive breathing.", checkQuestion: "What happens to the diaphragm during inhalation?", labels: ["Diaphragm", "Lungs", "Inhalation", "Exhalation"]),
        LearnChapter(id: "lungs_oxygen_journey", organID: "lungs", title: "From Air to Blood", category: .functionality, imageName: "lungs_oxygen_journey", imageLeft: true, learningGoal: "Connect breathing to oxygen delivery across the body.", explanation: "Air enters the lungs, oxygen diffuses into blood, and the circulation carries it toward the tissues. This chapter helps learners connect the respiratory and circulatory systems into one continuous journey.", keyFacts: ["Inhaled oxygen must enter blood before tissues can use it.", "The lungs and heart work as a linked system.", "Gas exchange is only one step in oxygen delivery."], caption: "Oxygen travels from inhaled air into the bloodstream and onward to the body.", checkQuestion: "What step must happen before oxygen can reach body tissues?", labels: ["Air", "Alveoli", "Blood", "Body Tissues"]),
        LearnChapter(id: "lungs_exercise_response", organID: "lungs", title: "Lungs During Exercise", category: .realLife, imageName: "lungs_exercise_response", imageLeft: false, learningGoal: "Understand why breathing changes during physical activity.", explanation: "During exercise, tissues use more oxygen and produce more carbon dioxide. The lungs respond by increasing ventilation so gas exchange can keep up with demand. Faster breathing supports performance and helps maintain blood gas balance.", keyFacts: ["Breathing rate rises during exercise.", "More air reaches the alveoli each minute.", "The respiratory and circulatory systems respond together."], caption: "The lungs increase airflow to support active muscles.", checkQuestion: "What happens to breathing during exercise?", labels: ["Increased Breathing Rate", "Oxygen Demand", "Active Muscles"]),
        LearnChapter(id: "lungs_smoking_effects", organID: "lungs", title: "Healthy vs Damaged Lung", category: .clinicalInsight, imageName: "lungs_smoking_effects", imageLeft: true, learningGoal: "Introduce how lung tissue can be affected by long-term damage.", explanation: "Healthy lung tissue provides large, flexible exchange surfaces. Damaged lung tissue may lose elasticity, develop inflammation, or exchange gases less efficiently. This chapter explains the idea without using frightening imagery.", keyFacts: ["Lung damage can reduce gas exchange efficiency.", "Airflow and elasticity both matter for healthy breathing.", "Prevention and healthy habits strongly affect lung function over time."], caption: "Healthy and damaged lung tissue support breathing differently.", checkQuestion: "Why damaged lungs exchange gases less efficiently?", labels: ["Healthy Lung", "Damaged Lung", "Alveoli", "Reduced Airflow"]),
        LearnChapter(id: "lungs_summary", organID: "lungs", title: "Lungs Summary", category: .summary, imageName: "lungs_summary", imageLeft: false, learningGoal: "Review how the lungs move air and exchange gases.", explanation: "The lungs rely on branching airways, tiny alveoli, and breathing muscles to support life. By reviewing the system as a whole, learners can connect organ structure, airflow, and gas exchange into one clear model.", keyFacts: ["Airways conduct air inward and outward.", "Alveoli exchange gases with blood.", "Breathing mechanics and circulation work together."], caption: "A recap of lung structure, airflow, and gas exchange.", checkQuestion: "Match lung structures with their respiratory roles?", labels: ["Airways", "Alveoli", "Gas Exchange", "Diaphragm"]),
    ]

    static let kidneys: [LearnChapter] = [
        LearnChapter(id: "kidneys_overview", organID: "kidneys", title: "Meet the Kidneys", category: .overview, imageName: "kidneys_overview", imageLeft: true, learningGoal: "Understand the kidneys as the body’s filtration organs.", explanation: "The kidneys filter blood, balance water and salts, and help remove waste through urine. They also support blood pressure regulation and chemical stability inside the body. Learn Mode begins with the whole organ before moving into its internal filtering system.", keyFacts: ["Most people have two kidneys.", "The kidneys help keep internal conditions stable.", "They work continuously as blood flows through them."], caption: "The kidneys help clean blood and regulate body balance.", checkQuestion: "What major body function the kidneys perform?", labels: ["Kidneys"]),
        LearnChapter(id: "kidneys_external_anatomy", organID: "kidneys", title: "Kidney Shape and Location", category: .anatomy, imageName: "kidneys_external_anatomy", imageLeft: false, learningGoal: "Learn where the kidneys sit and what they look like externally.", explanation: "The kidneys are bean-shaped organs located toward the back of the upper abdomen. Their position helps protect them while keeping them closely connected to major blood vessels and the urinary tract.", keyFacts: ["The kidneys sit behind the abdominal organs.", "They are positioned on either side of the spine.", "The right kidney often sits slightly lower than the left."], caption: "The kidneys sit high in the back of the abdomen on either side of the spine.", checkQuestion: "Where the kidneys are located relative to the spine?", labels: ["Right Kidney", "Left Kidney", "Ureter"]),
        LearnChapter(id: "kidneys_internal_anatomy", organID: "kidneys", title: "Cortex, Medulla, and Renal Pelvis", category: .anatomy, imageName: "kidneys_internal_anatomy", imageLeft: true, learningGoal: "Recognize the kidney’s major internal regions.", explanation: "Inside each kidney, the outer cortex and inner medulla help process blood and form urine. The renal pelvis collects formed urine before it passes into the ureter. These regions organize the filtering work of the organ.", keyFacts: ["The cortex forms the outer layer.", "The medulla contains deeper pyramidal regions.", "The renal pelvis collects urine before it exits."], caption: "The kidney’s internal anatomy channels fluid from filtering tissue into the urinary pathway.", checkQuestion: "Which kidney region collects urine before it enters the ureter?", labels: ["Cortex", "Medulla", "Renal Pelvis", "Ureter"]),
        LearnChapter(id: "kidneys_blood_filtration", organID: "kidneys", title: "Filtering the Blood", category: .functionality, imageName: "kidneys_blood_filtration", imageLeft: false, learningGoal: "Understand the basic idea of blood filtration in the kidneys.", explanation: "Blood enters the kidneys through renal arteries and is filtered through tiny units that remove waste while retaining important components. The kidneys then return cleaned blood to the circulation and direct filtered fluid toward urine formation.", keyFacts: ["Large amounts of blood pass through the kidneys every day.", "Filtration helps remove waste and balance the internal environment.", "Useful substances can be reabsorbed after initial filtering."], caption: "Kidney filtration helps separate waste from useful blood components.", checkQuestion: "What the kidneys remove from the blood?", labels: ["Renal Artery", "Filtration", "Cleaned Blood", "Waste Fluid"]),
        LearnChapter(id: "kidneys_nephron", organID: "kidneys", title: "The Nephron", category: .anatomy, imageName: "kidneys_nephron", imageLeft: true, learningGoal: "Learn the nephron as the kidney’s main working unit.", explanation: "Each kidney contains many nephrons, and each nephron filters blood and adjusts the fluid that will become urine. This small structure is where the kidney’s work becomes highly selective and efficient.", keyFacts: ["The nephron is the kidney’s functional unit.", "Filtration begins in the glomerulus.", "Tubular sections adjust fluid composition after filtration."], caption: "The nephron performs the kidney’s detailed filtering and balancing work.", checkQuestion: "Which structure is considered the kidney’s functional unit?", labels: ["Glomerulus", "Tubule", "Loop of Henle", "Collecting Duct"]),
        LearnChapter(id: "kidneys_urine_formation", organID: "kidneys", title: "Making Urine", category: .functionality, imageName: "kidneys_urine_formation", imageLeft: false, learningGoal: "Follow how filtered fluid becomes urine.", explanation: "Urine forms as filtered fluid is modified along the nephron. Water, salts, and useful molecules can be returned to the blood, while excess substances stay in the forming urine. The result is a controlled output rather than a simple waste dump.", keyFacts: ["Filtration is only the first step of urine formation.", "Reabsorption helps save water and useful molecules.", "Final urine reflects the body’s current balance needs."], caption: "Urine forms through filtration, reabsorption, and selective adjustment.", checkQuestion: "What process helps the body keep useful substances during urine formation?", labels: ["Filtrate", "Reabsorption", "Secretion", "Urine"]),
        LearnChapter(id: "kidneys_water_balance", organID: "kidneys", title: "Water and Salt Balance", category: .functionality, imageName: "kidneys_water_balance", imageLeft: true, learningGoal: "Understand how the kidneys help stabilize internal fluid balance.", explanation: "The kidneys constantly adjust how much water and salt leave the body. This helps maintain blood volume, hydration, and normal chemistry. It is one reason the kidneys are essential for overall homeostasis.", keyFacts: ["The kidneys help regulate hydration.", "Salt handling influences fluid balance.", "Hormones help guide kidney adjustments."], caption: "The kidneys help the body maintain stable water and salt levels.", checkQuestion: "Why the kidneys are important for hydration balance?", labels: ["Water Balance", "Salt Balance", "Blood Volume"]),
        LearnChapter(id: "kidneys_blood_pressure", organID: "kidneys", title: "Kidneys and Blood Pressure", category: .functionality, imageName: "kidneys_blood_pressure", imageLeft: false, learningGoal: "Learn how kidney function connects to blood pressure regulation.", explanation: "The kidneys influence blood pressure by controlling fluid volume and by releasing signals that affect blood vessel tone and salt handling. Their role links filtration to cardiovascular stability.", keyFacts: ["Fluid balance helps influence blood pressure.", "Kidney signaling systems can raise or lower pressure.", "Kidney disease can affect cardiovascular health."], caption: "The kidneys help regulate blood pressure through fluid and hormonal control.", checkQuestion: "How the kidneys help influence blood pressure?", labels: ["Blood Pressure", "Renin", "Fluid Volume"]),
        LearnChapter(id: "kidneys_stones", organID: "kidneys", title: "Kidney Stones", category: .clinicalInsight, imageName: "kidneys_stones", imageLeft: true, learningGoal: "Introduce kidney stones as a common urinary problem.", explanation: "Kidney stones form when minerals crystallize inside the urinary system. Small stones may pass on their own, while larger ones can block flow and cause pain. This chapter explains the basic concept without becoming graphic.", keyFacts: ["Stones form from concentrated minerals.", "They can move into the ureter.", "Blocking urine flow can cause pain and complications."], caption: "Kidney stones are solid mineral deposits that can disrupt urine flow.", checkQuestion: "Where a kidney stone can travel after forming in the kidney?", labels: ["Kidney Stone", "Kidney", "Ureter"]),
        LearnChapter(id: "kidneys_summary", organID: "kidneys", title: "Kidney Summary", category: .summary, imageName: "kidneys_summary", imageLeft: false, learningGoal: "Review kidney structure, filtration, and regulation in one recap.", explanation: "The kidneys filter blood, form urine, and help maintain internal balance. Understanding their structure—from whole organ to nephron—helps explain how the body regulates waste, water, salts, and blood pressure.", keyFacts: ["Kidneys filter blood and form urine.", "Nephrons perform the detailed filtering work.", "The kidneys help maintain homeostasis throughout the body."], caption: "A recap of kidney structure, filtration, and balance control.", checkQuestion: "Match kidney structures with their functions?", labels: ["Filtration", "Nephron", "Urine", "Homeostasis"]),
    ]

    static func chapters(for organID: String) -> [LearnChapter] {
        switch organID {
        case "heart": return heart
        case "brain": return brain
        case "lungs": return lungs
        case "kidneys": return kidneys
        default: return []
        }
    }
}
